#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""开机自启的安装 / 卸载。

做法：往「启动」文件夹放一个 .vbs，VBS 用 pythonw.exe 无窗口把管理器拉起来。
不用任务计划程序，是因为建任务要管理员权限，而启动文件夹不用。

    python autostart.py install     装
    python autostart.py remove      卸
    python autostart.py status      看状态
"""

import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPT = HERE / "model_manager.py"
STARTUP = Path(os.environ["APPDATA"]) / r"Microsoft\Windows\Start Menu\Programs\Startup"
VBS = STARTUP / "llm-manager.vbs"


def pythonw() -> str:
    """优先用 pythonw.exe —— 它不带控制台窗口，后台跑才不碍事"""
    exe = Path(sys.executable)
    w = exe.with_name("pythonw.exe")
    return str(w if w.exists() else exe)


def _write_vbs(path: Path, text: str) -> None:
    # wscript 按 ANSI 读 .vbs，中文用户名在 mbcs 下才不出乱码
    try:
        path.write_text(text, encoding="mbcs")
    except Exception:
        path.write_text(text, encoding="utf-8")


def install() -> int:
    if not SCRIPT.exists():
        print(f"[x] 找不到 {SCRIPT}")
        return 1
    STARTUP.mkdir(parents=True, exist_ok=True)

    # 这个文件保持纯 ASCII：wscript 按系统 ANSI 读 .vbs，混编码容易出岔子
    body = (
        "' Local LLM Manager autostart -- generated by autostart.py\r\n"
        "' Delete this file to disable autostart.\r\n"
        "Set sh = CreateObject(\"WScript.Shell\")\r\n"
        f'sh.CurrentDirectory = "{HERE}"\r\n'
        f'sh.Run """{pythonw()}"" ""{SCRIPT}""", 0, False\r\n'
    )
    _write_vbs(VBS, body)

    print("=" * 60)
    print("  开机自启已安装")
    print("=" * 60)
    print(f"  启动项  {VBS}")
    print(f"  解释器  {pythonw()}")
    print(f"  脚本    {SCRIPT}")
    print()
    print("  下次开机管理器会自动在后台跑起来，不会有窗口。")
    print("  想现在就用，双击 start.bat（这个有窗口，能看到日志）。")
    print("=" * 60)
    return 0


def remove() -> int:
    if VBS.exists():
        VBS.unlink()
        print(f"已删除启动项：{VBS}")
    else:
        print("本来就没装。")
    return 0


def status() -> int:
    print(f"启动项      {VBS}")
    print(f"状态        {'已安装' if VBS.exists() else '未安装'}")
    if VBS.exists():
        print("内容：")
        print(VBS.read_text(encoding="mbcs", errors="replace"))
    print(f"解释器      {pythonw()}")
    return 0


if __name__ == "__main__":
    cmd = (sys.argv[1] if len(sys.argv) > 1 else "status").lower()
    sys.exit({"install": install, "remove": remove, "status": status}
             .get(cmd, status)())
